### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by BlackIQ** [f-mohrechi/back-auth#1]
سلام،

یه سری چیزا رو میخواستم بگم بعد گفتم اگه یه وقت زیاد بشه ممکنه ناراحت بشید یا حس جالبی نداشته باشید. برای همین گفتم اول ازتون بپرسم الان یه سری چیزا رو بگم مشکلی اگه دارید که نگم اما ولی اگه مثلا اوکی هستید کم کم یه سریا رو عرض کنم.

ممنون.

**Comment by f-mohrechi** [comment]
سلام
آره حتما. درمورد این پروژه؟

**Comment by BlackIQ** [comment]
بله.

**Comment by f-mohrechi** [comment]
پس لطفا مستقیم بهم ایمیل بده.

**Comment by BlackIQ** [comment]
چشم حتما.

ایشو رو میبندم.
